substitutions:
  _IMAGE_TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Containerfile
      - -t
      - us-central1-docker.pkg.dev/homelab-personal-502823/apps/tip-split:${_IMAGE_TAG}
      - -t
      - us-central1-docker.pkg.dev/homelab-personal-502823/apps/tip-split:latest
      - .

images:
  - us-central1-docker.pkg.dev/homelab-personal-502823/apps/tip-split:${_IMAGE_TAG}
  - us-central1-docker.pkg.dev/homelab-personal-502823/apps/tip-split:latest
